### ISSUE TITLE
hypershift capi-ibm crashed while importing IBMPowerVSImage

### ISSUE THREAD

**Issue by dharaneeshvrd** [kubernetes-sigs/cluster-api-provider-ibmcloud#769]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

capi is crashed with the following stack trace.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x17326ef]

goroutine 460 [running]:
sigs.k8s.io/cluster-api-provider-ibmcloud/cloud/scope.(*PowerVSImageScope).CreateImageCOSBucket(0xc000a176d0)
	/workspace/cloud/scope/powervs_image.go:164 +0x56f
sigs.k8s.io/cluster-api-provider-ibmcloud/controllers.(*IBMPowerVSImageReconciler).getOrCreate(...)
	/workspace/controllers/ibmpowervsimage_controller.go:232
sigs.k8s.io/cluster-api-provider-ibmcloud/controllers.(*IBMPowerVSImageReconciler).reconcile(0x1e62aa8, 0xc000d1d080, 0xc000a176d0)
	/workspace/controllers/ibmpowervsimage_controller.go:148 +0x52b
sigs.k8s.io/cluster-api-provider-ibmcloud/controllers.(*IBMPowerVSImageReconciler).Reconcile(0xc000661cc0, {0x1e313f8, 0xc000650780}, {{{0xc00094f9c8, 0x12}, {0xc00094f9b0, 0x15}}})
	/workspace/controllers/ibmpowervsimage_controller.go:95 +0x4eb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0001d3080, {0x1e313f8, 0xc000650750}, {{{0xc00094f9c8, 0x1aadb20}, {0xc00094f9b0, 0x413a94}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001d3080, {0x1e31350, 0xc000578100}, {0x19b81c0, 0xc0000fd000})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001d3080, {0x1e31350, 0xc000578100})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x357
```

**What did you expect to happen:**

IBMPowerVSIMage should be successfully imported. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Used [k8s.gcr.io/capi-ibmcloud/cluster-api-ibmcloud-controller:v0.2.3](http://k8s.gcr.io/capi-ibmcloud/cluster-api-ibmcloud-controller:v0.2.3)

And IBMPowerVSImage spec:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: IBMPowerVSImage
metadata:
  annotations:
    cluster.x-k8s.io/cluster-name: hyp-tor-infra
  creationTimestamp: "2022-07-19T05:45:42Z"
  finalizers:
  - ibmpowervsimage.infrastructure.cluster.x-k8s.io
  generation: 1
  labels:
    cluster.x-k8s.io/cluster-name: hyp-tor-1
  name: 411.86.202206281844-0
  namespace: clusters-hyp-tor-1
  ownerReferences:
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: IBMPowerVSCluster
    name: hyp-tor-1
    uid: db15e862-f4af-4135-b8b6-bf1c8cce8123
  resourceVersion: "2792167"
  uid: b51f7a7f-fcbd-48e2-b554-3cb7ec72b41f
spec:
  bucket: rhcos-powervs-images-ca-tor
  clusterName: hyp-tor-1
  deletePolicy: delete
  object: rhcos-411-86-202206281844-0-ppc64le-powervs.ova.gz
  region: ca-tor
  serviceInstanceID: b5528922-15d6-49e5-98c7-e7b70b097808
  storageType: tier1
```

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mkumatag** [comment]
fixed via #768
