### ISSUE TITLE
periodic-capi-provider-ibmcoud-e2e-boskos-new is failing

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#893]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
periodic-capi-provider-ibmcoud-e2e-boskos-new is failing with following error:
```shell
Install complete.
panic: detect: not detected

goroutine 1 [running]:
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.DetectLocal()
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:72 +0x105
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.supportedLocale({0x0?, 0x0?})
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:90 +0x54
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.Init({0x7ff23aac1a18?, 0xc0001d7aa0?})
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:45 +0x2f
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.init()
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:41 +0xd2
+ EXIT_VALUE=2
```
Job logs - https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-capi-provider-ibmcoud-e2e-boskos-new/1573515157382893568

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mkumatag** [comment]
This is happening since the recent [release](https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v2.11.0) of ibmcloud cli and there is note mentioned in the release note as well.

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/12646029/192082658-3052297d-1a99-4c74-a276-a933b20c25e7.png">

But cli should handle the situation properly instead of panic, created https://github.com/IBM-Cloud/ibm-cloud-cli-release/issues/187 to track the issue.

Meanwhile will submit a PR to fix the `LANG` env variable.
